# maintainer: MohammadAmin Rahimi
version: "3.9"
services:
  db:
    container_name: coreDatabase
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - dbCore:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - core_net
  activemq:
    container_name: coreMq
    image: webcenter/activemq:latest
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - core_net
  app:
    # build: .
    image: amnrah/fum-cloud-notification-core-2023:cloud-v1.1.0
    container_name: coreApp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - activemq
    networks:
      - core_net
      - shared_net
volumes:
  dbCore:

networks:
  core_net:
  shared_net:
    external: true